support throw_exception_fmt_format with fmt < 8
Summary:
The class template `fmt::basic_format_string` was first introduced in release fmt-v8.

Fixes errors of the form:
```
folly/lang/Exception.h:170:10: error: no template named 'format_string' in namespace 'fmt'; did you mean 'format_to_n'?
  170 |     fmt::format_string<detail::throw_exception_arg_fmt_t<Args&&>...> str,
      |     ~~~~~^~~~~~~~~~~~~
      |          format_to_n
fmt/format.h:3425:37: note: 'format_to_n' declared here
 3425 | inline format_to_n_result<OutputIt> format_to_n(OutputIt out, std::size_t n,
      |                                     ^
```

Reviewed By: Gownta

Differential Revision: D65733915

fbshipit-source-id: 795b8f6a252091eb45fac396a3f78c896cb16633