Fix compilation of F14Table with exceptions disabled
Summary:
`F14Table` can fail to compile with exceptions disabled:

```
...\xplat\folly\container\detail\F14Table.h:2630:7: error: cannot use 'try' with exceptions disabled
      try {
      ^
```

On Windows it currently compiles via a non-intrinsic path due to the following `FOLLY_MOBILE` check in `F14IntrinsicsAvailability.h`:

```
#elif !FOLLY_MOBILE
#define FOLLY_F14_VECTOR_INTRINSICS_CONFIGURED 1
#else
#define FOLLY_F14_VECTOR_INTRINSICS_CONFIGURED 0
#endif
```

which will stop working once we properly set `FOLLY_MOBILE` to 0 on this platform.

Fix it by making the code work with exceptions disabled using `folly::catch_exception` similarly to D85084893.

Reviewed By: ilvokhin

Differential Revision: D85385076

fbshipit-source-id: a7c7fa32744226dc7aa8aafc7b8b2382fdac8f2d