fix compiler hints detection
Summary:
Addresses this compile error under GCC:
```
folly/lang/Hint-inl.h: In function ‘void folly::detail::compiler_must_not_predict(T&, std::false_type) [with T = folly::detail::distributed_mutex::DistributedMutex<>]’:
folly/lang/Hint-inl.h:118:3: error: impossible constraint in ‘asm’
  118 |   asm volatile("" : "+r"(t));
      |   ^~~
folly/lang/Hint-inl.h:118:3: error: non-memory output 0 must stay in memory
```

The cause is that `DistributedMutex<>` is trivially-copyable because `std::atomic<std::uintptr_t>` is trivially-copyable, even though neither is copy-constructible. The spec for trivial-copyability only considers whether there are no user-defined copy-constructors and, in these cases, there are not any, making the types trivially-copyable. The copy-constructors are defined as deleted, but they are not user-defined, so the types are not copy-constructible even though they are trivially-copyable.

Reviewed By: YifanYuan3

Differential Revision: D82135979

fbshipit-source-id: a5a36907aa76d1c64553393b6a78214606cbf92e