Fix OSS build
Summary:
hsthrift build failing thus: https://github.com/facebookincubator/hsthrift/actions/runs/9178162000/job/25237407394

```
AsyncSocket.cpp:1733:15: error: ‘BOOST_PP_IF’ was not declared in this scope; did you mean ‘BOOST_PP_IIF’?
 1733 |     iovec vec[BOOST_PP_IF(FOLLY_HAVE_VLA_01, count, kSmallIoVecSize)];
      |               ^~~~~~~~~~~
      |               BOOST_PP_IIF
```

Reviewed By: ot

Differential Revision: D57669498

fbshipit-source-id: 5570ace32a596294a4b444673d2d58a4822bbf7e