folly/python/executor use getpid instead of os.getpid for finalization issues
Summary:
The issue was during deep finalization of cpython the imports might not exist anymore by the time `__del__` methods run.  So we use the c `getpid` function instead

folly has a portability Unistd.h we can use for this so it works on windows

Error was
```
exception ignored in: 'folly.executor.NotificationQueueAsyncioExecutor.__dealloc__'
AttributeError: 'NoneType' object has no attribute 'getpid'
```

Differential Revision: D76789663

fbshipit-source-id: 781e586745d78fbe6391923c48c85b6ac4ed84cd