fix windows folly build
Summary:
fix windows folly build
 * fmt requires unicode, add /utf-8 msvc flag
 * Settings.cpp was using C++20 struct init that MSVC is strict about, change to regular init
 * MSVC can't handle the parameter to RegexMatchCache::is_span_compatible,  extract out the check that needs E to into the
std::enable_if_t
 * ContainsTest needed cast to size_t for std::min to work
 * Disable tests that don't compile for windows

Test Plan:

local build with: `python ./build/fbcode_builder/getdeps.py build --src-dir=. folly`

before, [broken](https://github.com/facebook/folly/actions/runs/11402111839/job/31726415001#step:42:629)
```
Z:\installed\fmt--08ZeFppBnK_Qz90kx-Yjd0crzRfSn6gIcQEVrX89l4\include\fmt\base.h(458): error C2338: Unicode support requires compiling with /utf-8
[2/842] Building CXX object CMakeFiles\folly_base.dir\folly\Conv.cpp.obj
```

then...
```
C:\Users\alex\local\folly\folly/container/RegexMatchCache.h(434): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'folly::detail::fallback_span::span<const size_t,18446744073709551615>'
C:\Users\alex\local\folly\folly/container/RegexMatchCache.h(434): note: No constructor could take the source type, or constructor overload resolution was ambiguous
ninja: build stopped: subcommand failed.
Command '['Y:\\build\\folly\\succeed.bat', '&&', 'Y:\\installed\\cmake-_qm1f2PWnzobdL5bp69h3vWFzt0Lbzikp_cDemrJG0U\\bin\\cmake.exe', '--build', 'Y:\\build\\folly', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed`
```