Fix FixedString taking address of temporary array
Summary:
[Folly] Fix `FixedString` taking address of temporary array with latest versions of GCC.

```
In file included from folly/test/FixedStringTest.cpp:20:
folly/FixedString.h: In instantiation of 'constexpr folly::BasicFixedString<Char, N>& folly::BasicFixedString<Char, N>::erase(std::size_t, std::size_t) [with Char = char; long unsigned int N = 26; std::size_t = long unsigned int]':
folly/test/FixedStringTest.cpp:421:14:   required from here
folly/FixedString.h:1466:11: error: taking address of temporary array
```

Reviewed By: ericniebler

Differential Revision: D13602969

fbshipit-source-id: fefa24eb00021b205498cbc7ebf7c43595d6aa8c