avoid append-va-arg in FOLLY_SAFE_CHECK
Summary:
Since clang has a mode which rejects the append-va-arg construct as implemented in `FOLLY_PP_DETAIL_APPEND_VA_ARG`.

Do this by avoiding appending va-args to other args. Instead, take advantage of `operator()` as a workaround.

Avoids:
```
folly/Preprocessor.h:72:46: error: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Werror,-Wgnu-zero-variadic-macro-arguments]
#define FOLLY_PP_DETAIL_APPEND_VA_ARG(...) , ##__VA_ARGS__
                                             ^
```

Reviewed By: luciang

Differential Revision: D33863906

fbshipit-source-id: 14912aca73e332ab811db4c0ac772a2d224a0666