fix local variable shadow
Summary:
D1720014 line 183 in HHWheelTimer.h broke proxygen/facebook/httpclient clang build:

./folly/io/async/HHWheelTimer.h:183:17: error: declaration shadows a local variable [-Werror,-Wshadow]
Wrapper(F fn) : fn_(std::move(fn)) {}
^
./folly/io/async/HHWheelTimer.h:181:28: note: previous declaration is here
void scheduleTimeoutFn(F fn, std::chrono::milliseconds timeout) {

I renamed the `fn` in `Wrapper` to `f`.

Test Plan: pass

Reviewed By: seanc@fb.com

Subscribers: njormrod, folly-diffs@, subodh, seanc, kmdent, fma

FB internal diff: D1724835

Signature: t1:1724835:1418052896:d9a72230d4fd1a4a734a33142966fe796f4fd362