fix for S439847 msan build failure
Summary:
title, many lionhead harness msan build are broken due to the common dependency in folly. Which when built in opt-msan mode would activate the `-Werror,-Wswitch-enum` flag but not in opt-asan mode.

```
$ buck2 build mode/opt-msan fbcode//folly/compression:compression
Action failed: fbcode//folly/compression:compression (cxx_compile Compression.cpp (pic))
Local command returned non-zero exit code 1
Reproduce locally: `env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbcode/ee1775f533258208/cxx_compile/_buck_5adf8237ee832ee2 ...<omitted>... /5b5c233b68b7ee39/folly/compression/__compression__/__dep_files_intermediaries__/Compression.cpp.pic (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
fbcode/folly/compression/Compression.cpp:1207:11: error: 9 enumeration values not explicitly handled in switch: 'LZMA_SEEK_NEEDED', 'LZMA_RET_INTERNAL1', 'LZMA_RET_INTERNAL2'... [-Werror,-Wswitch-enum]
  switch (rc) {
          ^~
1 error generated.
```

we investigated with toolchain team but it is still unclear what causes the discrepency: https://fb.workplace.com/groups/lionhead/posts/1881271849013329/?comment_id=1881281902345657&reply_comment_id=1881311812342666

the fix in this diff should be reasonable for now to unblock the sev and a couple user request that msan field crash do not auto close due to the broken build.

Reviewed By: yfeldblum

Differential Revision: D61568823

fbshipit-source-id: 7b295b1b12f0ce286c28ce68660c6f912ea95352