Add missing return in AsyncPipe move assignment operator
Summary:
I'm using AsyncPipe heavily in D22593723. At one iteration I needed to assign with move a holding object and it wouldn't compile because the operator doesn't return any value

Here's the error: `folly/experimental/coro/AsyncPipe.h:54:3: error: control reaches end of non-void function [-Werror,-Wreturn-type]`

Reviewed By: yfeldblum

Differential Revision: D22593724

fbshipit-source-id: 53f27b95c1dff0068a375291d4ee6f445f892dd9