Compiler workaround for Task::co_withExecutor
Summary:
I replaced this odd-looking friend declaration by a new private helper in `Task`.

```
  friend TaskWithExecutor<T> co_withExecutor(
      Executor::KeepAlive<>, Task<T>) noexcept;
```

I originally added this friend because:
- An older MSVC was not treating the `Task` hidden friend `co_withExecutor` as having `Task<T>`-level access to `TaskWithExecutor<T>`.
- 99% of builds did not care about the friend, and it made the old MSVC work.

Unfortunately, it turned out that some sporadic builds use `-Werror=non-template-friend`, which is unhappy with the above.

```
folly/coro/Task.h:722:39: error: friend declaration 'folly::coro::TaskWithExecutor<T> folly::coro::co_withExecutor(folly::Executor::KeepAlive<>, folly::coro::Task<T>)' declares a non-template function [-Werror=non-template-friend]
  722 |       Executor::KeepAlive<>, Task<T>) noexcept;
      |                                       ^~~~~~~~
folly/coro/Task.h:722:39: note: (if this is not what you intended, make sure the function template has already been declared and add '<>' after the function name here)
cc1plus: all warnings being treated as errors
```

I don't see a good way to make friend access work universally, and suppressing the (overall valid) warning seemed a bit yucky, so I opted for the extra helper function that I was initially trying to avoid.

Reviewed By: maksdamir, Yingquan-Y

Differential Revision: D77943184

fbshipit-source-id: a99e2242f78cf120f6fd6c4d27aa30f40781209e