Add missing gflags #include in tests (#1051)
Summary:
Some tests fail to compile because gflags.h is not included:

    .../folly/test/FormatOtherTest.cpp: In function 'int main(int, char**)':
    .../folly/test/FormatOtherTest.cpp:113:3: error: 'gflags' has not been declared
       gflags::ParseCommandLineFlags(&argc, &argv, true);
       ^~~~~~

The tests compile without issue on Travis CI without this patch, but I
don't see how that's possible.

Include gflags.h explicitly to fix the compilation of these tests.
Pull Request resolved: https://github.com/facebook/folly/pull/1051

Reviewed By: aary

Differential Revision: D14400709

Pulled By: yfeldblum

fbshipit-source-id: 73999a940f45511373d3922ea8eb782a27af0008