Ignore -Wnontrivial-memcall
Summary:
llvm21 introduces a new flag `-Wnontrivial-memcall`.
An error is produced when building the 21 compiler. For example, `buck2 build mode/opt -mllvmfb21 admarket/adranker:adranker`. This diff suppresses the warning by casting the pointer.

```
buck-out/v2/gen/fbcode/folly/container/__small_vector__/fbefa47a5ee6297d/buck-headers/folly/container/small_vector.h:1105:21: error: first argument in call to 'memcpy' is a pointer to non-trivially copyable type 'value_type' (aka 'folly::basic_fbstring<char, std::char_traits<char>, std::allocator<char>, facebook::admarket::MicroFBStringCore<char>>') [-Werror,-Wnontrivial-memcall]
 1105 |       std::memcpy(u.buffer(), o.u.buffer(), MaxInline * kSizeOfValue);
      |                     ^
buck-out/v2/gen/fbcode/folly/container/__small_vector__/fbefa47a5ee6297d/buck-headers/folly/container/small_vector.h:570:9: note: in instantiation of member function 'folly::small_vector<folly::basic_fbstring<char, std::char_traits<char>, std::allocator<char>, facebook::admarket::MicroFBStringCore<char>>>::moveInlineStorageRelocatable' requested here
  570 |         moveInlineStorageRelocatable(std::move(o));
      |         ^
buck-out/v2/gen/fbcode/configerator/structs/sigrid/lib/features/interface/__definitions-cpp2-types__/40263075dcb80e73/buck-headers/configerator/structs/sigrid/lib/features/interface/gen-cpp2/definitions_types.h:2888:48: note: in instantiation of member function 'folly::small_vector<folly::basic_fbstring<char, std::char_traits<char>, std::allocator<char>, facebook::admarket::MicroFBStringCore<char>>>::small_vector' requested here
 2888 |     ::new (std::addressof(value_.caffe2Blobs)) T(std::move(t));
      |                                                ^
buck-out/v2/gen/fbcode/configerator/structs/sigrid/lib/features/interface/__definitions-cpp2-types__/40263075dcb80e73/buck-headers/configerator/structs/sigrid/lib/features/interface/gen-cpp2/definitions_types.h:2681:9: note: in instantiation of function template specialization 'facebook::sigrid::GeneralizedPredictionType::set_caffe2Blobs<>' requested here
 2681 |         set_caffe2Blobs(std::move(rhs.value_.caffe2Blobs));
      |         ^
buck-out/v2/gen/fbcode/folly/container/__small_vector__/fbefa47a5ee6297d/buck-headers/folly/container/small_vector.h:1105:21: note: explicitly cast the pointer to silence this warning
 1105 |       std::memcpy(u.buffer(), o.u.buffer(), MaxInline * kSizeOfValue);
      |                     ^
      |                   (void*)

Reviewed By: yfeldblum

Differential Revision: D90258719

fbshipit-source-id: f88d92e4f3ed72bafc04176c0dcae2d1b6171734