Fix -Wimplicit-int-enum-cast
Summary:
Clang 21 introduces a new flag `-Wimplicit-int-enum-cast` and diff fixes the warnings by static cast. The `static_cast<bits_t>()` produce the same result as `bit_t{}`, but clang21 now treats it as an error. The `static_cast` just makes it more explicit.

```
Action failed: fbcode//fbpkg/experiments/chicken/eggcarton/maybe:maybe (cxx_compile Maybe.cpp)
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action c4eaa5b59f01e9bbdd91e0071c936648aae17c5f412d7c91f6ab247078ffafa9:148`
stdout:
stderr:
In file included from fbcode/fbpkg/experiments/chicken/eggcarton/maybe/Maybe.cpp:1:
In file included from buck-out/v2/gen/fbcode/fbpkg/experiments/chicken/eggcarton/maybe/__maybe__/c9ce15b8dc290867/buck-headers/fbpkg/experiments/chicken/eggcarton/maybe/Maybe.h:8:
In file included from buck-out/v2/gen/fbcode/folly/coro/__gtest_helpers__/d95a6d2f892ed531/buck-headers/folly/coro/GtestHelpers.h:19:
In file included from buck-out/v2/gen/fbcode/folly/coro/__blocking_wait__/6face595a3570ac1/buck-headers/folly/coro/BlockingWait.h:21:
In file included from buck-out/v2/gen/fbcode/folly/coro/__task__/625a4bacd32fce53/buck-headers/folly/coro/Task.h:36:
In file included from buck-out/v2/gen/fbcode/folly/coro/__base_promise__/6ec65bb0957fe201/buck-headers/folly/coro/BasePromise.h:23:
In file included from buck-out/v2/gen/fbcode/folly/coro/__value_or_error__/ead3787b10600297/buck-headers/folly/coro/ValueOrError.h:20:
In file included from buck-out/v2/gen/fbcode/folly/result/__try__/524e7b0418c32acc/buck-headers/folly/result/try.h:20:
In file included from buck-out/v2/gen/fbcode/folly/result/__result__/1f1393257acbae63/buck-headers/folly/result/result.h:26:
In file included from buck-out/v2/gen/fbcode/folly/result/__rich_error_base__/fbac3d5aee3bc4ce/buck-headers/folly/result/rich_exception_ptr.h:21:
buck-out/v2/gen/fbcode/folly/result/detail/__rich_exception_ptr_storage__/f1f68c461732763a/buck-headers/folly/result/detail/rich_exception_ptr_storage.h:326:21: error: implicit conversion from 'int' to enumeration type 'bits_t' is invalid in C++ [-Werror,-Wimplicit-int-enum-cast]
  326 |       return bits_t{0};
      |                    ~^
buck-out/v2/gen/fbcode/folly/result/detail/__rich_exception_ptr_storage__/f1f68c461732763a/buck-headers/folly/result/detail/rich_exception_ptr_storage.h:328:34: error: implicit conversion from 'uintptr_t' (aka 'unsigned long') to enumeration type 'bits_t' is invalid in C++ [-Werror,-Wimplicit-int-enum-cast]
  328 |     return bits_t{data_.uintptr_ & 0x7};
      |                  ~~~~~~~~~~~~~~~~^~~~~
In file included from fbcode/fbpkg/experiments/chicken/eggcarton/maybe/Maybe.cpp:1:
In file included from buck-out/v2/gen/fbcode/fbpkg/experiments/chicken/eggcarton/maybe/__maybe__/c9ce15b8dc290867/buck-headers/fbpkg/experiments/chicken/eggcarton/maybe/Maybe.h:8:
In file included from buck-out/v2/gen/fbcode/folly/coro/__gtest_helpers__/d95a6d2f892ed531/buck-headers/folly/coro/GtestHelpers.h:19:
In file included from buck-out/v2/gen/fbcode/folly/coro/__blocking_wait__/6face595a3570ac1/buck-headers/folly/coro/BlockingWait.h:21:
In file included from buck-out/v2/gen/fbcode/folly/coro/__task__/625a4bacd32fce53/buck-headers/folly/coro/Task.h:36:
In file included from buck-out/v2/gen/fbcode/folly/coro/__base_promise__/6ec65bb0957fe201/buck-headers/folly/coro/BasePromise.h:23:
In file included from buck-out/v2/gen/fbcode/folly/coro/__value_or_error__/ead3787b10600297/buck-headers/folly/coro/ValueOrError.h:20:
In file included from buck-out/v2/gen/fbcode/folly/result/__try__/524e7b0418c32acc/buck-headers/folly/result/try.h:20:
In file included from buck-out/v2/gen/fbcode/folly/result/__result__/1f1393257acbae63/buck-headers/folly/result/result.h:26:
buck-out/v2/gen/fbcode/folly/result/__rich_error_base__/fbac3d5aee3bc4ce/buck-headers/folly/result/rich_exception_ptr.h:554:39: error: implicit conversion from 'uintptr_t' (aka 'unsigned long') to enumeration type 'bits_t' is invalid in C++ [-Werror,-Wimplicit-int-enum-cast]
  553 |         bits_t{
      |               ~
  554 |             B::OWNS_EXCEPTION_PTR_and | B::owned_eptr_UNKNOWN_TYPE_masked_eq});
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
buck-out/v2/gen/fbcode/folly/result/__rich_error_base__/fbac3d5aee3bc4ce/buck-headers/folly/result/rich_exception_ptr.h:680:12: note: in instantiation of member function 'folly::detail::rich_exception_ptr_impl<folly::rich_exception_ptr, folly::detail::rich_exception_ptr_packed_storage>::rich_exception_ptr_impl' requested here
  680 |     return Derived{detail::force_slow_rtti_t{}, std::move(e)};
      |            ^
buck-out/v2/gen/fbcode/folly/result/__result__/1f1393257acbae63/buck-headers/folly/result/result.h:166:34: note: in instantiation of member function 'folly::detail::rich_exception_ptr_impl<folly::rich_exception_ptr, folly::detail::rich_exception_ptr_packed_storage>::from_exception_ptr_slow' requested here
  166 |       : rep_{rich_exception_ptr::from_exception_ptr_slow(std::move(eptr))} {}
      |                                  ^
In file included from fbcode/fbpkg/experiments/chicken/eggcarton/maybe/Maybe.cpp:1:
In file included from buck-out/v2/gen/fbcode/fbpkg/experiments/chicken/eggcarton/maybe/__maybe__/c9ce15b8dc290867/buck-headers/fbpkg/experiments/chicken/eggcarton/maybe/Maybe.h:8:
In file included from buck-out/v2/gen/fbcode/folly/coro/__gtest_helpers__/d95a6d2f892ed531/buck-headers/folly/coro/GtestHelpers.h:19:
In file included from buck-out/v2/gen/fbcode/folly/coro/__blocking_wait__/6face595a3570ac1/buck-headers/folly/coro/BlockingWait.h:21:
In file included from buck-out/v2/gen/fbcode/folly/coro/__task__/625a4bacd32fce53/buck-headers/folly/coro/Task.h:36:
In file included from buck-out/v2/gen/fbcode/folly/coro/__base_promise__/6ec65bb0957fe201/buck-headers/folly/coro/BasePromise.h:23:
In file included from buck-out/v2/gen/fbcode/folly/coro/__value_or_error__/ead3787b10600297/buck-headers/folly/coro/ValueOrError.h:20:
In file included from buck-out/v2/gen/fbcode/folly/result/__try__/524e7b0418c32acc/buck-headers/folly/result/try.h:20:
In file included from buck-out/v2/gen/fbcode/folly/result/__result__/1f1393257acbae63/buck-headers/folly/result/result.h:26:
buck-out/v2/gen/fbcode/folly/result/__rich_error_base__/fbac3d5aee3bc4ce/buck-headers/folly/result/rich_exception_ptr.h:619:27: error: implicit conversion from 'uintptr_t' (aka 'unsigned long') to enumeration type 'const bits_t' (aka 'const folly::detail::rich_exception_ptr_base_storage::bits_t') is invalid in C++ [-Werror,-Wimplicit-int-enum-cast]
  619 |     constexpr bits_t bits{[]() {
      |                          ~^~~~~~
  620 |       if constexpr (std::derived_from<Ex, rich_error_base>) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  621 |         // Redundant with `rich_error.h` asserts, hence no manual test.
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  622 |         static_assert(detail::has_offset0_base<Ex, rich_error_base>);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  623 |         return bits_t::OWNS_EXCEPTION_PTR_and |
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  624 |             bits_t::IS_RICH_ERROR_BASE_masked_eq;
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  625 |       } else if constexpr (std::derived_from<Ex, OperationCancelled>) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  626 |         // We only want the throwing version here, since nothrow OC uses a
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  627 |         // different ctor, and a non-owned copy of a leaky singleton.  This
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  628 |         // should never fire since `StubNothrowOperationCancelled` doesn't
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  629 |         // derive from `std::exception`, and `OperationCancelled` will soon
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  630 |         // no longer be directly constructible.
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  631 |         static_assert(
      |         ~~~~~~~~~~~~~~
  632 |             // FIXME: This one will go away:
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  633 |             std::is_same_v<const Ex, const OperationCancelled> ||
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  634 |             std::is_same_v<const Ex, const StubThrownOperationCancelled>);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
buck-out/v2/gen/fbcode/folly/result/__result__/1f1393257acbae63/buck-headers/folly/result/result.h:175:49: note: in instantiation of function template specialization 'folly::detail::rich_exception_ptr_impl<folly::rich_exception_ptr, folly::detail::rich_exception_ptr_packed_storage>::rich_exception_ptr_impl<folly::OperationCancelled>' requested here
  175 |   explicit non_value_result(stopped_result_t) : rep_{OperationCancelled{}} {}
      |                                                 ^
4 errors generated.
Buck UI: https://www.internalfb.com/buck2/a500b265-c545-4196-94e9-4f6eee317c89
Network: Up: 30MiB  Down: 96MiB  (reSessionID-5b1002e2-e915-4f25-9435-2a15509eed1e)
Loading targets.   Remaining      0/797                                                                      2955 dirs read, 63986 targets declared
Analyzing targets. Remaining      0/29058                                                                    1106665 actions, 1563055 artifacts declared
Executing actions. Remaining      0/170628                                                                   7:32:33.7s exec time total
Command: build.    Finished 222 local, 4961 remote, 23315 cache (82% hit)                                    3:36:06.8s exec time cached (47%)
Time elapsed: 24.8s
BUILD FAILED
Failed to build 'fbcode//fbpkg/experiments/chicken/eggcarton/maybe:maybe (cfg:opt-linux-x86_64-fbcode-platform010-clang21-no-san#d38e97381a05e873)'

Reviewed By: yfeldblum

Differential Revision: D90865534

fbshipit-source-id: e7072dfbf2bcbbb5dfbdde5ea070341083f4f933