Fix compiler warnings in small_vector
Summary:
Fix a bug in small_vector reported as a warning via gcc.

```
folly/small_vector.h: In instantiation of 'constexpr const size_t folly::small_vector<short int, 10>::MaxInline':
folly/small_vector.h:1183:56:   required from 'class folly::small_vector<short int, 10>'
bits/stl_stack.h:134:47:   required from 'class std::stack<short int, folly::small_vector<short int, 10> >'
folly/small_vector.h:462:36: error: division 'sizeof (short int*) / sizeof (short int)' does not compute the number of array elements [-Werror=sizeof-pointer-div]
  462 |       constexpr_max(sizeof(Value*) / sizeof(Value), RequestedMaxInline)};
      |                     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
```

Reviewed By: yfeldblum

Differential Revision: D27688663

fbshipit-source-id: 8da5b017c597c542826e26f2c36b0e3b46e87ed9