Fix compilation of F14Table with exceptions disabled
Summary:
`F14Table` can fail to compile with exceptions disabled:

```
In file included from arvr\libraries\hzanim\string_table\src\StringTable.cpp:4:
In file included from arvr\libraries\hzanim\string_table\include\hzanim/BasicStringTable.h:8:
In file included from .\xplat\folly/container/F14Map.h:41:
In file included from .\xplat\folly/container/detail/F14Policy.h:29:
.\xplat\folly/container/detail/F14Table.h:1880:7: error: cannot use 'throw' with exceptions disabled
      throw;
      ^
```

On Windows it currently compiles via a non-intrinsic path due to the following `FOLLY_MOBILE` check in `F14IntrinsicsAvailability.h`:

```
#elif !FOLLY_MOBILE
#define FOLLY_F14_VECTOR_INTRINSICS_CONFIGURED 1
#else
#define FOLLY_F14_VECTOR_INTRINSICS_CONFIGURED 0
#endif
```

which will stop working once we properly set `FOLLY_MOBILE` to 0 on this platform.

Fix it by making the code work with exceptions disabled using `folly::catch_exception`.

Reviewed By: ot

Differential Revision: D85084893

fbshipit-source-id: ad190e9072fc246374804e1755cc799addd828d9