fix SerialExecutor test under MSVC
Summary:
```
folly\executors\test\SerialExecutorTest.cpp(222): error C3493: 'kNumIterations' cannot be implicitly captured because no default capture mode has been specified
```

Reviewed By: ot

Differential Revision: D55835991

fbshipit-source-id: aba3e0972427fda8d408d02be7b1ed75beb22024