add defaulted CursorBase copy/move ctor/assign
Summary:
They are implicitly defined as defaulted, but this behavior is deprecated and trips clang warning `deprecated-copy-with-dtor`. Add explicit definitions as defaulted.

```
folly/io/Cursor.h:830:3: error: definition of implicit copy assignment operator for 'CursorBase<folly::io::Cursor, const folly::IOBuf>' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated-copy-with-dtor]
  ~CursorBase() = default;
  ^
folly/io/Cursor.h:1079:7: note: in implicit copy assignment operator for 'folly::io::CursorBase<folly::io::Cursor, const folly::IOBuf>' first required here
class Cursor : public CursorBase<Cursor, const IOBuf> {
      ^
```

Reviewed By: Filip-F

Differential Revision: D56046741

fbshipit-source-id: 3aa88827256af136741987dba9cc3699b1b5e2f8