constexpr_strlen workaround for GCC 11+
Summary:
`__builtin_strlen(((const char*)(&<anonymous>)))` is not a constant expression
in GCC. Pass an unsigned int on GCC 11+ so the alternate `constexpr std::size_t constexpr_strlen_internal(const Char* s, unsigned)` is used instead.

```
/builddir/build/BUILD/folly-2022.07.11.00/folly/portability/Constexpr.h:101:43:   in 'constexpr' expansion of 'folly::detail::constexpr_strlen_internal<char>(s, 0)'
/builddir/build/BUILD/folly-2022.07.11.00/folly/portability/Constexpr.h:48:29: error: '__builtin_strlen(((const char*)(&<anonymous>)))' is not a constant expression
   48 |   return FOLLY_DETAIL_STRLEN(s);
      |                             ^                                                                                                                                                                                                                                                                                   /builddir/build/BUILD/folly-2022.07.11.00/folly/test/FixedStringTest.cpp:432:21: error: non-constant condition for static assertion
  432 |   static_assert(26u == tmp0.size(), "");
      |                 ~~~~^~~~~~~~~~~~~~
/builddir/build/BUILD/folly-2022.07.11.00/folly/test/FixedStringTest.cpp:433:19: error: non-constant condition for static assertion
  433 |   static_assert(y == tmp0, "");
      |                 ~~^~~~~~~
/builddir/build/BUILD/folly-2022.07.11.00/folly/test/FixedStringTest.cpp:435:21: error: non-constant condition for static assertion
  435 |   static_assert(24u == tmp1.size(), "");
      |                 ~~~~^~~~~~~~~~~~~~
/builddir/build/BUILD/folly-2022.07.11.00/folly/test/FixedStringTest.cpp:436:44: error: non-constant condition for static assertion
  436 |   static_assert("abcdefghijklmnopqrstuvwx" == tmp1, "");
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/builddir/build/BUILD/folly-2022.07.11.00/folly/test/FixedStringTest.cpp:438:20: error: non-constant condition for static assertion
  438 |   static_assert(2u == tmp2.size(), "");
      |                 ~~~^~~~~~~~~~~~~~
/builddir/build/BUILD/folly-2022.07.11.00/folly/test/FixedStringTest.cpp:439:22: error: non-constant condition for static assertion
  439 |   static_assert("ax" == tmp2, "");
      |                 ~~~~~^~~~~~~
gmake[2]: *** [CMakeFiles/fixed_string_test.dir/build.make:79: CMakeFiles/fixed_string_test.dir/folly/test/FixedStringTest.cpp.o] Error 1
```

Reviewed By: Gownta

Differential Revision: D38132357

fbshipit-source-id: 6bb84134eb5fdad6b2b5be8f392651081c306218