fix folly.symbolizer build error
Summary:
```
fbcode/folly/io/IOBuf.cpp:802:7:   required from here
third-party/glog/include/glog/logging.h:621:9: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘std::nullptr_t’)
  621 |   (*os) << v;
      |   ~~~~~~^~~~
```

bisect lead me to D69618772, and revert worked

Reviewed By: yfeldblum

Differential Revision: D71049514

fbshipit-source-id: d705f539a2640bf961218a2f8e6d5e0b12c2e885