Fix test/ProducerConsumerQueueTest.cpp build break
Summary:
The Folly `make check` build is broken with Clang on OS X.

This diff fixes the following break in `test/ProducerConsumerQueueTest.cpp`:

  In file included from ProducerConsumerQueueTest.cpp:17:
  ../../folly/ProducerConsumerQueue.h:55:18: error: no member named 'bad_alloc' in namespace 'std'
        throw std::bad_alloc();

The problem is a missing `#include <memory>` in `folly/ProducerConsumerQueue.h`.

Reviewed By: djwatson

Differential Revision: D3361252

fbshipit-source-id: d740914f54ede5617abc16437ab2e20a7376f6e5