fix violation of deprecated-declarations in Range
Summary:
`Range` uses `std::char_traits` over all its param types, which does not conform.

Unblocks Xcode 15.

Fixes the following report:
```
folly/Range.h:197:12: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
      std::char_traits<typename std::remove_const<value_type>::type>;
           ^
folly/Range.h:110:20: note: in instantiation of template class 'folly::Range<const unsigned char *>' requested here
    const typename Range<Iter>::value_type& needle);
                   ^
folly/Range.h:1495:15: note: while substituting deduced template arguments into function template 'qfind' [with Iter = const unsigned char *]
inline size_t qfind(
              ^
```

Reviewed By: NSProgrammer

Differential Revision: D46823611

fbshipit-source-id: 0f27b26ecd6d4f48ef210c126f1f502597e8903b