Fix a DistributedMutex build failure under MSVC
Summary:
[Folly] Fix a `DistributedMutex` build failure under MSVC, which does not have great support for whatever is happening here, which in this case is a case of variable templates with SFINAE.

Not much information to go on, so this is a best guess:
```
folly/synchronization/DistributedMutex-inl.h(563): fatal error C1001: An internal error has occurred in the compiler.
```

Reviewed By: aary

Differential Revision: D15837884

fbshipit-source-id: 8da993cc27373f86728963d2112812c15a4f34ea