Fix libfollylogging link dependency (#872)
Summary:
The folly logging library introduced a new shared library:
libfollylogging. folly::init recently started to depend on on
libfollylogging's initLoggingOrDie(). The problem is that libfolly is
never linked with libfollylogging, leading to the following error
upon application link time:

    /usr/local/lib/libfolly.so: undefined reference to
    folly::initLoggingOrDie(folly::Range<char const*>)

This patch forces libfollylogging to implicitly link with libfolly
through the removal of libfollylogging altogether.

Note that logging/InitWeak.cpp has been added to the source list.
This was previously omitted.
Closes https://github.com/facebook/folly/pull/872

Reviewed By: simpkins

Differential Revision: D8530795

Pulled By: danobi

fbshipit-source-id: 280fbc2170364621e9a682ae38cf812c23bde5e5