fix incorrect shift in get_bit_at test under MSVC
Summary:
The intention is to create a value of type `T` with a single bit set, but `1UL << i` is incorrect. Rather, `T(T{1} << i)` must be used.

Shifts are permitted only by less than the width of the type. `1UL << 32` is valid only if `1UL` is 64 bits. But in the MSVC builds on github, `1UL` is 32 bits, making the shift invalid, and causing the test to fail.

Fixes this test failure under MSVC:
```
[ RUN      ] BitsAllUintsTest/3.GetBitAt
D:\a\folly\folly\folly\lang\test\BitsTest.cpp(625): error: Value of: folly::get_bit_at(in, kBitSize + i)
  Actual: false
Expected: true
i=32
[  FAILED  ] BitsAllUintsTest/3.GetBitAt, where TypeParam = unsigned __int64 (0 ms)
```

Differential Revision: D77464671