Set no-unused-function for conda
Summary:
Expident workaround for the following error seen in the conda platform:

```
Action failed: fbcode//folly:demangle (cxx_compile Demangle.cpp (pic))
Local command returned non-zero exit code 1
Reproduce locally: `env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbcode/2448932244264a7a/cxx_compile/_buck_82cc5e55290df196 ...<omitted>... ode/folly/__demangle__/44084b15fb594fce/.cpp.cxx_compile_argsfile -fPIC -
c fbcode/folly/Demangle.cpp (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
In file included from buck-out/v2/gen/fbcode/fc587ed39bbe1976/conda/buck_integration/toolchains/___cxx_toolchain_build_env_for_default__/__env__/x86_64-conda-linux-gnu/include/c++/11.2.0/cassert:44,
                 from buck-out/v2/gen/fbcode/folly/lang/__cstring_view__/32f93c02d1a1f095/buck-headers/folly/lang/cstring_view.h:19,
                 from buck-out/v2/gen/fbcode/folly/hash/__hash__/3a4fadd9a480aaef/buck-headers/folly/hash/Hash.h:54,
                 from buck-out/v2/gen/fbcode/folly/__fbstring__/2c30058166dd96b8/buck-headers/folly/FBString.h:40,
                 from buck-out/v2/gen/fbcode/folly/__demangle__/bdca4bd4524d68c6/buck-headers/folly/Demangle.h:19,
                 from fbcode/folly/Demangle.cpp:17:
buck-out/v2/gen/fbcode/folly/lang/__cstring_view__/32f93c02d1a1f095/buck-headers/folly/lang/cstring_view.h: In instantiation of 'static constexpr const Char* folly::basic_cstring_view<Char, Traits>::check_strin
g(const Char*, size_t) [with Char = char; Traits = std::char_traits<char>; size_t = long unsigned int]':
buck-out/v2/gen/fbcode/folly/lang/__cstring_view__/32f93c02d1a1f095/buck-headers/folly/lang/cstring_view.h:96:27:   required from 'constexpr folly::basic_cstring_view<Char, Traits>::basic_cstring_view(const Cha
r*, std::size_t) [with Char = char; Traits = std::char_traits<char>; std::size_t = long unsigned int]'
buck-out/v2/gen/fbcode/folly/lang/__cstring_view__/32f93c02d1a1f095/buck-headers/folly/lang/cstring_view.h:469:31:   required from here
buck-out/v2/gen/fbcode/folly/lang/__cstring_view__/32f93c02d1a1f095/buck-headers/folly/lang/cstring_view.h:52:17: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
   52 |     assert(!str && !len || Traits::length(str) == len);
      |            ~~~~~^~~~~~~
fbcode/folly/Demangle.cpp:72:18: error: 'void {anonymous}::rust_demangle_callback({anonymous}::poison)' declared 'static' but never defined [-Werror=unused-function]
   72 | FOLLY_ERASE void rust_demangle_callback(poison);
      |                  ^~~~~~~~~~~~~~~~~~~~~~
```

The compiler used:

```
% ~/fbsource/buck-out/v2/gen/fbcode/conda/buck_integration/toolchains/___prebuilt_cxx_toolchain_tools_env__/c7d381314798df6c/fbpkg/env/bin/x86_64-conda-linux-gnu-c++ --version
x86_64-conda-linux-gnu-c++ (conda-forge gcc 11.4.0-13) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Reviewed By: ShukantPal

Differential Revision: D84857291

fbshipit-source-id: eefac0b2635cc9455e78502af789bcdf13030295