Fix folly Travis build caused by D17506766.
Summary:
/home/folly/folly/experimental/test/QuotientMultiSetTest.cpp:60:29: error:
missing template arguments before 'reader'
     folly::QuotientMultiSet reader(data);

Reviewed By: vitaut

Differential Revision: D17959566

fbshipit-source-id: 02fec44b3d644eea0213895aa4df70349ef7d062