fix violations of missing-braces in folly/fibers/
Summary:
Fixes the following observed violations:

```
folly/fibers/async/test/AsyncTest.cpp: In lambda function:
folly/fibers/async/test/AsyncTest.cpp:315:49: error: missing braces around initializer for ‘std::__array_traits<bool, 3>::_Type’ {aka ‘bool [3]’} [-Werror=missing-braces]
  315 |       std::array<bool, 3> cs{false, false, false};
      |                                                 ^
folly/fibers/async/test/AsyncTest.cpp:333:49: error: missing braces around initializer for ‘std::__array_traits<bool, 3>::_Type’ {aka ‘bool [3]’} [-Werror=missing-braces]
  333 |       std::array<bool, 3> cs{false, false, false};
      |                                                 ^
```

Reviewed By: Orvid

Differential Revision: D37367428

fbshipit-source-id: fb017ada4bfadd7a68170efdc6e9fbe90d54b7f3