Fix deprecated literal operator in folly/Range.h
Summary:
Required for LLVM-17.

Fixes
```
     45 fbcode/folly/__range__/buck-headers/folly/Range.h:1680:41: error: identifier '_sp' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
     37 fbcode/folly/__range__/buck-headers/folly/Range.h:1702:44: error: identifier '_sp' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
     37 fbcode/folly/__range__/buck-headers/folly/Range.h:1697:45: error: identifier '_sp' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
     37 fbcode/folly/__range__/buck-headers/folly/Range.h:1692:45: error: identifier '_sp' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
     37 fbcode/folly/__range__/buck-headers/folly/Range.h:1686:44: error: identifier '_sp' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
```

Reviewed By: Gownta

Differential Revision: D56208165

fbshipit-source-id: ca37a5b2fe65a638ccdffb8b59eb794e8ec658d5