remove the deprecated and unused `fbcode_compiler_flags`
Summary:
It's kind of a surprise that `fbcode_compiler_flags_override` didn't include `compiler_flags` and supplying an empty list here would erase all compiler flags, making them useless under `Fbcode` variants.

Good news is that under folly `rg fbcode_compiler_flags` returned nothing. In fact, if you try to pass a non-empty one today, you get buck yelling at you
```
Error running analysis for `fbsource//xplat/folly/debugging/exception_tracer:exception_tracer_callbacksFbcode (cfg:dev-linux-x86_64-fbcode-platform010-libcxx-clang19-asan-ubsan-dev#fa66e5f09421e0aa)`

Caused by:
    0: Error in configured node dependency, dependency chain follows (-> indicates depends on, ^ indicates same configuration as previous):
              fbsource//xplat/folly/debugging/exception_tracer:exception_tracer_callbacksFbcode (cfg:dev-linux-x86_64-fbcode-platform010-libcxx-clang19-asan-ubsan-dev#fa66e5f09421e0aa)
           -> fbcode//folly/debugging/exception_tracer:compatibility (^)

    1: looking up unconfigured target node `fbcode//folly/debugging/exception_tracer:compatibility`
    2: Error loading targets in package `fbcode//folly/debugging/exception_tracer` for target `fbcode//folly/debugging/exception_tracer:compatibility`
    3: Error evaluating build file: `fbcode//folly/debugging/exception_tracer:BUCK`
    4: Traceback (most recent call last):
         * fbcode/folly/debugging/exception_tracer/BUCK:383, in <module>
             fbcode_target(
         * tools/build_defs/fbcode_macros/build_defs/build_file_migration.bzl:12, in fbcode_target
             return _kind(*args, **kwargs)
         * tools/build_defs/fbcode_macros/build_defs/cpp_library.bzl:247, in cpp_library
             attrs = cpp_library_attributes(name, **kwargs)
       error: Found `fbcode_compiler_flags` extra named parameter(s) for call to tools/build_defs/fbcode_macros/build_defs/cpp_library.bzl.cpp_library_attributes
          --> tools/build_defs/fbcode_macros/build_defs/cpp_library.bzl:247:13
           |
       247 |     attrs = cpp_library_attributes(name, **kwargs)
           |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |

```

Originally introduced by D22164766 for memory.

Reviewed By: skrueger, yfeldblum

Differential Revision: D84637162

fbshipit-source-id: 79716a785bd77cdfea1344ae66a9549dac8199fd