fix deps for iobufs
Summary:
Iobuf.pyx imports from executor but doesn't have the dep for it.  Not sure how this worked before

The issue is on windows

```
import folly.iobuf as _fbthrift_iobuf
File "folly/iobuf.pyx", line 1, in init folly.iobuf
ImportError: DLL load failed while importing executor: The specified module could not be found.
```

Reviewed By: Orvid

Differential Revision: D78036307

fbshipit-source-id: 7079c5f8cf7e1ef417b58642649a2e4d6d2720a1