fix fbstring_core::initSmall for llvm-19 + ubsan and page boundaries
Summary:
Fixes this violation of warning `undefined-reinterpret-cast`:
```
folly/FBString.h:703:22: error: dereference of type 'Char **' that was reinterpret_cast from type 'const Char *const' has undefined behavior [-Werror,-Wundefined-reinterpret-cast]
  703 |         ml_.data_ = *reinterpret_cast<Char**>(const_cast<Char*>(data));
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Also fixes the logic to avoid extended loads crossing page boundaries.

And removes the alignment check already in there, since relevant platforms have unaligned loads to which fixed-size `memcpy` can be lowered.

Reviewed By: ot, meyering, dmm-fb

Differential Revision: D69907498

fbshipit-source-id: 5bb0bde550883163a0fe41021be7b665989d0d24