Revert D101656943
Summary:
This diff reverts D101656943
Cause the following build error on Artemis
```
rm -rf ~/coleman_build arvr/firmware/wearables/apps/artemis/dragon/coleman/build/* && make -C arvr/firmware/wearables/apps/artemis/dragon/coleman/ ursa_major_test
make: Entering directory '/data/users/agupta10/fbsource/arvr/firmware/wearables/apps/artemis/dragon/coleman'
set -e
buck2 build @//arvr/mode/artemis/opt //arvr/firmware/wearables/apps/artemis/dragon/coleman:coleman_ursa_major_test \
        --out /home/agupta10/coleman_build
ln -snf /home/agupta10/coleman_build /data/users/agupta10/fbsource/arvr/firmware/wearables/apps/artemis/dragon/coleman/build || true
File changed (since mergebase): fbsource//arvr/firmware/silicon/fcv/neuvo/src/neuvo_eye_tracking/BUCK
File changed (since mergebase): fbsource//arvr/firmware/silicon/fcv/neuvo/src/neuvo_eye_tracking/src/NeuvoEyeTracking.cpp
File changed (since mergebase): fbsource//arvr/firmware/silicon/fcv/neuvo/src/neuvo_hand_tracking/BUCK
58 additional file change events (since mergebase)
File Watcher fresh instance: new mergebase, cleared graph state, cleared dep files
File changed: fbsource//www/scripts/build/artifacts/CalledWhenRevisionIsChangedScriptController.log
Reproduce locally: `env -C "$(buck2 root --kind project)" -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbsource/247e2e76ef18c65 ...<omitted>... nternals__/bed0359c454d10a5/.cpp.cxx_compile_argsfile -c arvr/libraries/eye/engine/ourcv/polygon.cpp (run `buck2 log what-failed` to get the full command)`
stdout:
Checkout succeeded: XT_XCC_TIE_EC094FF6/C22D979C0B85
License file: /data/users/agupta10/fbsource/buck-out/v2/tmp/fbsource/247e2e76ef18c653/cxx_compile/polygon.cpp/FCV3_MV110GP_temp_y8ov6eox
No server used
In file included from arvr/libraries/eye/engine/ourcv/polygon.cpp:3:
In file included from arvr/libraries/eye/engine/ourcv/polygon.h:7:
In file included from arvr/libraries/eye/engine/ourcv/OurCvTypes.h:9:
In file included from arvr/libraries/eye/engine/common/BasicContainers.h:7:
In file included from arvr/libraries/eye/engine/common/containers/BoundableVector.h:20:
In file included from arvr/libraries/eye/engine/common/containers/SafeSmallVector.h:11:
In file included from ./xplat/folly/small_vector.h:17:
./xplat/folly/container/small_vector.h:669:17: error: no member named 'lexicographical_compare_three_way' in namespace 'std'; did you mean 'lexicographical_compare'?
    return std::lexicographical_compare_three_way(
           ~~~~~^
/data/users/agupta10/fbsource/arvr/third-party/toolchains/xtensa/XtDevTools/install/builds/RJ-2025.5-linux/FCV3_MV110GP/xtensa-elf/include/c++/v1/__algorithm/lexicographical_compare.h:42:1: note: 'lexicographical_compare' declared here
lexicographical_compare(_InputIterator1 __first1, _InputIterator1 __last1,
^
1 error generated.
stderr:
[2026-06-15 19:35:13,550 INFO] Core name being used FCV3_MV110GP on release RJ-2025.5
[2026-06-15 19:35:19,034 ERROR] Xtensa subprocess finished with exit code 1
args:
/data/users/agupta10/fbsource/arvr/third-party/toolchains/xtensa/XtDevTools/install/tools/RJ-2025.5-linux/XtensaTools/bin/xt-clang++ --xtensa-system=/data/users/agupta10/fbsource/arvr/third-party/toolchains/xtensa/XtDevTools/install/tools/RJ-2025.5-linux/XtensaTools/config --xtensa-core=FCV3_MV110GP -o buck-out/v2/art/fbsource/arvr/libraries/eye/engine/ourcv/__Internals__/output_artifacts/__objects__/polygon.cpp.o buck-out/v2/tmp/fbsource/247e2e76ef18c653/cxx_compile/polygon.cpp/.cpp.cxx_compile_argsfile -c arvr/libraries/eye/engine/ourcv/polygon.cpp
env:
FNP_IP_PRIORITY=6
FNP_IP_ENV=1
XTENSA_TOOLS=/data/users/agupta10/fbsource/arvr/third-party/toolchains/xtensa/XtDevTools/install/tools/RJ-2025.5-linux/XtensaTools/Tools
FLEXLM_NO_CKOUT_INSTALL_LIC=1
XTENSA_LICENSE_RETRIES=10:1
FLEXLM_TIMEOUT=1000000
FLEXLM_DIAGNOSTICS=6
XTENSA_TOOLS_PATH=/data/users/agupta10/fbsource/arvr/third-party/toolchains/xtensa/XtDevTools/install/tools/RJ-2025.5-linux/XtensaTools
XTENSA_CONFIG_PATH=/data/users/agupta10/fbsource/arvr/third-party/toolchains/xtensa/XtDevTools/install/builds/RJ-2025.5-linux/FCV3_MV110GP
XTENSAD_LICENSE_FILE=/data/users/agupta10/fbsource/buck-out/v2/tmp/fbsource/247e2e76ef18c653/cxx_compile/polygon.cpp/FCV3_MV110GP_temp_y8ov6eox:5920@snc-edalic-arvr-cdns01.thefacebook.com:5920@snc-edalic-arvr-temp01.thefacebook.com:5920@lhr-edalic-arvr-test01.thefacebook.com:5920@ash-edalic-arvr-cdns01.thefacebook.com

Buck UI: https://www.internalfb.com/buck2/c3625aa5-d696-46bb-9dcd-affa9e58811b
Network: Up: 210KiB  Down: 102MiB  (reSessionID-989acf96-acbc-42f5-9f86-60201a8ddd09)
Loading targets.     Remaining      0/3880                                                                                                                                                                                             419083 dirs read, 249361 targets declared
Analyzing targets.   Remaining      0/64424                                                                                                                                                                                            529509 actions, 1033938 artifacts declared
Executing actions.   Remaining      0/157936                                                                                                                                                                                           35:33:50.3s exec time total
Command: build.    Finished 5 local, 48132 cache (99% hit)                                                                                                                                                                             35:33:32.1s exec time cached (99%)
Time elapsed: 35.6s
Buck UI: https://www.internalfb.com/buck2/c3625aa5-d696-46bb-9dcd-affa9e58811b
BUILD FAILED
Failed to build 'fbsource//arvr/libraries/eye/engine/ourcv:Internals (cfg:opt-xtensa-xos-xtensa#26251f3bc9830ae0)'
make: *** [Makefile:376: build_ursa_major_test] Error 3
make: Leaving directory '/data/users/agupta10/fbsource/arvr/firmware/wearables/apps/artemis/dragon/coleman'
```

Depends on D101656943

Reviewed By: agupta10fb

Differential Revision: D108701135

fbshipit-source-id: 6757edc47ec74a87eb991a1f40864ea8f6344e3a