remove some clang warning flags so liburing external lib compiles
Summary:
Liburing 3rd party library has clang warnings when built with these clang flags (`Wnested-anon-types`, `Wzero-length-array`) . This diff disables these warnings so that liburing can be built with buck modes that have these clang warnings (like fbsource//arvr/mode/platform010/dev-tsan for example).

For more context the target I am building is `buck build --keep-going --flagfile fbsource//arvr/mode/platform010/dev-tsan fbsource//arvr/libraries/immersion/reconstruction/servers:pc_app --show-output` from this [diff](https://www.internalfb.com/diff/D76423109) which eventually pulls in liburing as a dependency. The reason we haven't had this problem is probablly because arvr never pulled this file as a dependency.

Here is one example of the warnings from liburing:
```
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action af046bdfd535f946862491a4b63393d0cf0c07c095756bde2d6048b7a8bf9d8a:145`
stdout:
stderr:
In file included from fbcode/thrift/lib/cpp2/server/ThriftServer.cpp:20:
In file included from buck-out/v2/gen/fbcode/b5444731ba6ad33e/thrift/lib/cpp2/server/__io_uring_util__/buck-headers/thrift/lib/cpp2/server/IOUringUtil.h:20:
In file included from buck-out/v2/gen/fbcode/b5444731ba6ad33e/folly/experimental/io/__io_uring_backend__/buck-headers/folly/experimental/io/IoUringBackend.h:17:
In file included from buck-out/v2/gen/fbcode/b5444731ba6ad33e/folly/io/async/__io_uring_backend__/buck-headers/folly/io/async/IoUringBackend.h:42:
In file included from buck-out/v2/gen/fbcode/b5444731ba6ad33e/folly/io/async/__io_uring_zero_copy_buffer_pool__/buck-headers/folly/io/async/IoUringZeroCopyBufferPool.h:25:
In file included from buck-out/v2/gen/fbsource/b5444731ba6ad33e/third-party/liburing/__uring__/buck-headers/liburing.h:18:
buck-out/v2/gen/fbsource/b5444731ba6ad33e/third-party/liburing/__uring__/buck-headers/liburing/io_uring.h:38:3: error: anonymous types declared in an anonymous union are an extension [-Werror,-Wnested-anon-types]
                struct {
                ^
buck-out/v2/gen/fbsource/b5444731ba6ad33e/third-party/liburing/__uring__/buck-headers/liburing/io_uring.h:46:3: error: anonymous types declared in an anonymous union are an extension [-Werror,-Wnested-anon-types]
                struct {
                ^
buck-out/v2/gen/fbsource/b5444731ba6ad33e/third-party/liburing/__uring__/buck-headers/liburing/io_uring.h:92:3: error: anonymous types declared in an anonymous union are an extension [-Werror,-Wnested-anon-types]
                struct {
                ^
buck-out/v2/gen/fbsource/b5444731ba6ad33e/third-party/liburing/__uring__/buck-headers/liburing/io_uring.h:107:12: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
                __u8    cmd[0];
                            ^
buck-out/v2/gen/fbsource/b5444731ba6ad33e/third-party/liburing/__uring__/buck-headers/liburing/io_uring.h:98:3: error: anonymous types declared in an anonymous union are an extension [-Werror,-Wnested-anon-types]
                struct {
                ^
buck-out/v2/gen/fbsource/b5444731ba6ad33e/third-party/liburing/__uring__/buck-headers/liburing/io_uring.h:775:28: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
                struct io_uring_buf     bufs[0];
                                             ^
buck-out/v2/gen/fbsource/b5444731ba6ad33e/third-party/liburing/__uring__/buck-headers/liburing/io_uring.h:769:3: error: anonymous types declared in an anonymous union are an extension [-Werror,-Wnested-anon-types]
                struct {
```

Reviewed By: dmm-fb

Differential Revision: D76390208

fbshipit-source-id: 2dc969895f4afe2ac1e65dbdb7736f4ddbcdf08c