fix gcc-5 build
Summary:
```lang=bash
folly/test/SmallLocksBenchmark.cpp:212:18: error: use of undeclared identifier 'sqrt'
  double stdev = sqrt(accum / (results.size() - 1));
                 ^
folly/test/SmallLocksBenchmark.cpp:221:20: error: use of undeclared identifier 'sqrt'
  double stddev2 = sqrt(variance);
                   ^
2 errors generated.
```
Add the missing header.

Reviewed By: yfeldblum

Differential Revision: D4386343

fbshipit-source-id: 79c3dcae32c62f9b6d162862deabccf5fea7eaef