Add missing gflags #include in tests
Some tests fail to compile because gflags.h is not included:

    .../folly/test/FormatOtherTest.cpp: In function 'int main(int, char**)':
    .../folly/test/FormatOtherTest.cpp:113:3: error: 'gflags' has not been declared
       gflags::ParseCommandLineFlags(&argc, &argv, true);
       ^~~~~~

The tests compile without issue on Travis CI without this patch, but I
don't see how that's possible.

Include gflags.h explicitly to fix the compilation of these tests.