let IoUringBackend work with multiple versions of liburing.h
Summary:
The signature of `io_uring_prep_cancel` changed between releases, breaking callers. Allow the caller in `IoUringBackend` at least to work with both. Do this via implicit casts from an intermediate type.

The change is introduced upstream in: https://github.com/axboe/liburing/commit/d84c29b19ed0b130000619cff40141bb1fc3615b.
The change is semi-fixed upstream in: https://github.com/axboe/liburing/commit/5e63866e719c47f13a0c43c90019fae912b328d8.

```
In file included from folly/experimental/io/IoUringBackend.cpp:25:
folly/experimental/io/IoUringBackend.h:637:35: error: cannot initialize a parameter of type 'void *' with an rvalue of type 'uint64_t' (aka 'unsigned long')
      ::io_uring_prep_cancel(sqe, reinterpret_cast<uint64_t>(cancel_sqe), 0);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/liburing.h:379:73: note: passing argument to parameter 'user_data' here
static inline void io_uring_prep_cancel(struct io_uring_sqe *sqe, void *user_data,
                                                                        ^
```

Differential Revision: D37271994

fbshipit-source-id: a4c6f7f9a8f060444bcd30b09827372ccb345c42