folly/detail/MemoryIdler.cpp: fix platform010-exposed build errors
Summary:
We should all be migrating to platform010, for the improved performance of its
generated code and for its improved diagnostics/portability.

cast PTHREAD_STACK_MIN to size_t, since with glibc-2.34, it now has type long

This avoids the following errors:

  folly/detail/MemoryIdler.cpp:140:18: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'long' [-Werror,-Wsign-compare]

Differential Revision: D32057242

fbshipit-source-id: 1fae2aec5829a837e2aecf068f6c2c061c911e95