folly: fixup AsyncTimeoutTest on windows
Summary:
In D14702587 I made a change to workaround an ICE in gcc 8.
It turns out to be a gift that keeps giving; with the code as-is
on windows we now encounter:

```
folly\io\async\test\AsyncTimeoutTest.cpp(29): error C3493: 'expected' cannot be implicitly captured because no default capture mode has been specified
```

Adding `expected` to the capture list yields this error with gcc, either with or without the reference:

```
stderr: folly/io/async/test/AsyncTimeoutTest.cpp:29:45: error: lambda capture 'expected' is not required to be captured for this use [-Werror,-Wunused-lambda-capture]
      AsyncTimeout::make(manager, [&value, &expected]() noexcept { value = expected; });
                                         ~~~^~~~~~~~
1 error generated.
```

the solution is to make `expected` not be `const`.

Reviewed By: yfeldblum

Differential Revision: D14721418

fbshipit-source-id: b65c17414c161b9dee7f269b2e2a22a980766a6c