Fix recvmmsg signature
Summary:
This fixes the following error when building folly (via thrift) on Ubuntu Focal with clang 10 and likely other systems:

```
/tmp/fbcode_builder_getdeps-ZhomeZvagrantZfbthriftZbuildZfbcode_builder/repos/github.com-facebook-folly.git/folly/net/NetOps.cpp:34:32:
error: conflicting types for 'recvmmsg' extern "C" FOLLY_ATTR_WEAK int recvmmsg(
                               ^
/usr/include/x86_64-linux-gnu/sys/socket.h:199:12: note: previous declaration is
here extern int recvmmsg (int __fd, struct mmsghdr *__vmessages,
           ^
```

`sys/socket.h` defines `recvmmsg` with signed flags:
```
extern int recvmmsg (int __fd, struct mmsghdr *__vmessages,
                     unsigned int __vlen, int __flags,
                     struct timespec *__tmo);
```
which is consistent with the docs: https://man7.org/linux/man-pages/man2/recvmmsg.2.html. So the fix is to make flags signed in the folly's definition.

Reviewed By: Gownta

Differential Revision: D37756904

fbshipit-source-id: 4c46deb76a5580170f7be8db4af95b83c267e267