Ignore return value explicitly
Summary:
Our CVM builds started failing due to unused result in folly. Explicitly ignoring the return value to unblock the builds and Conveyors. Folly folks, please advise on what is the best approach here.

Gaia:
https://www.internalfb.com/services/whatsapp_theia/gaia/conveyor/whatsapp_theia/gaia/releases/132.1/nodes/Contbuild%20Tracking%20Node%20(tw.whatsapp.gaia.sandbox.rc)/runs/1264965308793014?pipeline_names[0]=WA%20Gaia%20Conveyor%20Pipeline&node_details_tab=run_details_summary

Orchestrator:
https://www.internalfb.com/ci/results/slp/33127629113547235?tag=conveyor_artifact%3A%3A%2F%2Fwhatsapp%2Ftheia%2Ftee%2Fsrc%2Fcvm%2Forchestrator%2Fsandbox%3Atw.whatsapp.theia.orchestrator.sandbox.public.prod

```
fbcode/folly/io/async/IoUringEvent.cpp:84:7: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
   84 |       fileops::read(eventFd_->fd(), &val, sizeof(val));
      |       ^~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Reviewed By: ot, CookieComputing

Differential Revision: D90684709

fbshipit-source-id: d81acde1234b2397b4cdf73c57c013566c6d599b