Ninja update to avoid build fail on python3.13 (#2392)
Summary:
When building from scratch folly on python 3.13, here is the issue you will encounter:
```
Extract /private/tmp/follyt/downloads/ninja-v1.10.2.tar.gz -> /private/tmp/follyt/extracted/ninja-v1.10.2.tar.gz
Building ninja...
 ---
+ cd /private/tmp/follyt/extracted/ninja-v1.10.2.tar.gz/ninja-1.10.2 && \
+ /opt/homebrew/opt/python@3.13/bin/python3.13 \
+      configure.py \
+      --bootstrap
Traceback (most recent call last):
  File "/private/tmp/follyt/extracted/ninja-v1.10.2.tar.gz/ninja-1.10.2/configure.py", line 26, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
Command '['/opt/homebrew/opt/python@3.13/bin/python3.13', 'configure.py', '--bootstrap']' returned non-zero exit status 1.
!! Failed
```
(`python3.13 ./build/fbcode_builder/getdeps.py build --scratch-path /tmp/follyt`)

This is because the version `1.10.2` of ninja uses `pipes`, which has been deprecated since python 3.11 and removed in python 3.13. [^1]

This PR changes the ninja dependency from 1.10.2 to 1.12.1.

[^1]: https://docs.python.org/3/library/pipes.html

Pull Request resolved: https://github.com/facebook/folly/pull/2392

Reviewed By: yfeldblum

Differential Revision: D76523565

Pulled By: Orvid

fbshipit-source-id: 8ba5b96b3a01334ab9b04e62c80588868273bb25