Use assert() instead of DCHECK
Summary:
We were seeing the following build failures on i386:
```
In file included from folly/stats/detail/BufferedStat.h:151,
                 from folly/stats/QuantileEstimator.h:20,
                 from folly/stats/QuantileEstimator.cpp:17:
folly/stats/detail/BufferedStat-inl.h: In member function 'void folly::detail::BufferedStat<DigestT, ClockT>::doUpdate(folly::detail::BufferedStat<DigestT, ClockT>::TimePoint, const std::unique_lock<folly::SharedMutexImpl<false> >&, folly::detail::BufferedStat<DigestT, ClockT>::UpdateMode)':
folly/stats/detail/BufferedStat-inl.h:72:3: error: there are no arguments to 'DCHECK' that depend on a template parameter, so a declaration of 'DCHECK' must be available [-fpermissive]
   72 |   DCHECK(g.owns_lock());
      |   ^~~~~~
```

My best guess is some kind of argument dependent lookup complication.

This diff sidesteps the issue by using plain old `assert()` instead

Reviewed By: yfeldblum

Differential Revision: D24375147

fbshipit-source-id: d702d883fcabc548e8f4969207e265abf21acf2b