let Range never specialize basic_string_view with non-char types
Summary:
The libc++ implementation of `std::basic_string_view` explicitly deprecates any specializations except for a select list. `folly::Range` attempts to avoid such specialization, and it worked with some platforms. This attempt was introduced in {D62275652}, but it is incomplete.

Now we completely avoid such specialization using a more complete technique.

```
usr/include/c++/v1/__fwd/string_view.h:22:41: error: 'char_traits<std::shared_ptr<splat_engine::ConstellusEngine>>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 19, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
   22 | template <class _CharT, class _Traits = char_traits<_CharT> >
      |                                         ^
folly/Range.h:642:18: note: in instantiation of default argument for 'basic_string_view<std::remove_cv_t<std::remove_pointer_t<shared_ptr</* ... */>>>>' required here
  642 |             std::basic_string_view<std::remove_cv_t<std::remove_pointer_t<ValueType>>>,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
folly/Traits.h:260:1: note: in instantiation of template class 'folly::Range<std::shared_ptr<splat_engine::ConstellusEngine> *>::StringViewType<std::shared_ptr</* ... */>>' requested here
  260 | using _t = typename T::type;
      | ^
folly/Range.h:691:19: note: in instantiation of template type alias '_t' requested here
  691 |                   _t<StringViewType<ValueType>>,
      |                   ^
folly/Range.h:696:13: note: while substituting prior template arguments into non-type template parameter [with Tgt = std::nullptr_t, ValueType = value_type]
  696 |   constexpr operator Tgt() const noexcept(
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  697 |       std::is_nothrow_constructible<Tgt, Iter const&, size_type>::value) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  698 |     return Tgt(b_, walk_size());
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  699 |   }
      |   ~
```

Reviewed By: drodriguez

Differential Revision: D71203191

fbshipit-source-id: 6440a8dacb7dfb0acd67a038f1cb8ff41dab2790