Remove unneeded variable in folly/test/SynchronizedTest.cpp
Summary:
Required for LLVM-17.

Fixes
```
     36 fbcode/folly/test/SynchronizedTest.cpp:727:17: error: variable 'gId' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
```

Reviewed By: Orvid

Differential Revision: D56207839

fbshipit-source-id: f26c4f78171a5693f251d3491ae595a20ca8c5d2