fix gcc-5 build
Summary:
Clang with libgcc-5 reported:
```lang=bash
folly/experimental/test/BitsTest.cpp:249:16: error: use of undeclared identifier 'pow'
  auto value = pow(2, bits) * (negate ? -2.0 : 2.0) / 3.0;
               ^
```
Add missing include statement, and elaborate with the namespace.

Reviewed By: yfeldblum

Differential Revision: D4385807

fbshipit-source-id: a847dd439cd4c9f28ea8f222aa4ab60876949d13