fix github CI tests on windows (#2256)
Summary:
These were [failing on github](https://github.com/facebook/folly/actions/runs/9923539772/job/27413784313#step:43:30071)

 * Fix use of regex in test in FsUtilTest.cpp
 * MSVC std::current_exception() exception_ptr return values are not comparable, was breaking ExceptionTest
 * Fix lookup of executable path on windows, which was breaking SSL test

Pull Request resolved: https://github.com/facebook/folly/pull/2256

Test Plan:
```
python build/fbcode_builder/getdeps.py build --src-dir=. folly
python build/fbcode_builder/getdeps.py test folly
```

before, broken:
```
1/6 Test  https://github.com/facebook/folly/issues/941: ssl_session_test.SSLSessionTest.BasicTest ...................***Failed    0.03 sec
Note: Google Test filter = SSLSessionTest.BasicTest
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SSLSessionTest
[ RUN      ] SSLSessionTest.BasicTest
unknown file: error: C++ exception with description "boost::filesystem::read_symlink: The system cannot find the path specified [system:3]: "/proc/self/exe"" thrown in SetUp().
[  FAILED  ] SSLSessionTest.BasicTest (4 ms)
[----------] 1 test from SSLSessionTest (4 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (4 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SSLSessionTest.BasicTest

 1 FAILED TEST

    Start  942: ssl_session_test.SSLSessionTest.NullSessionResumptionTest
2/6 Test  https://github.com/facebook/folly/issues/936: HHWheelTimerTest.HHWheelTimerTest.GetTimeRemaining ..........   Passed    0.06 sec
    Start 1029: lang_exception_test.ExceptionTest.current_exception
3/6 Test  https://github.com/facebook/folly/issues/942: ssl_session_test.SSLSessionTest.NullSessionResumptionTest ...***Failed    0.04 sec
Note: Google Test filter = SSLSessionTest.NullSessionResumptionTest
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SSLSessionTest
[ RUN      ] SSLSessionTest.NullSessionResumptionTest
unknown file: error: C++ exception with description "boost::filesystem::read_symlink: The system cannot find the path specified [system:3]: "/proc/self/exe"" thrown in SetUp().
[  FAILED  ] SSLSessionTest.NullSessionResumptionTest (6 ms)
[----------] 1 test from SSLSessionTest (6 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (7 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SSLSessionTest.NullSessionResumptionTest

 1 FAILED TEST

4/6 Test  https://github.com/facebook/folly/issues/839: fs_util_test.Simple.UniquePathDefaultModel ..................***Failed    0.08 sec
Note: Google Test filter = Simple.UniquePathDefaultModel
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Simple
[ RUN      ] Simple.UniquePathDefaultModel
5/6 Test https://github.com/facebook/folly/issues/1029: lang_exception_test.ExceptionTest.current_exception .........***Failed    0.02 sec
Note: Google Test filter = ExceptionTest.current_exception
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ExceptionTest
[ RUN      ] ExceptionTest.current_exception
D:\a\folly\folly\folly\lang\test\ExceptionTest.cpp(238): error: Expected equality of these values:
  std::current_exception()
    Which is: 16-byte object <20-44 C1-6B 9B-01 00-00 10-44 C1-6B 9B-01 00-00>
  folly::current_exception()
    Which is: 16-byte object <30-3B C1-6B 9B-01 00-00 20-3B C1-6B 9B-01 00-00>
D:\a\folly\folly\folly\lang\test\ExceptionTest.cpp(247): error: Expected equality of these values:
  std::current_exception()
    Which is: 16-byte object <40-3F C1-6B 9B-01 00-00 30-3F C1-6B 9B-01 00-00>
  folly::current_exception()
    Which is: 16-byte object <20-44 C1-6B 9B-01 00-00 10-44 C1-6B 9B-01 00-00>
[  FAILED  ] ExceptionTest.current_exception (0 ms)
[----------] 1 test from ExceptionTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ExceptionTest.current_exception

 1 FAILED TEST

6/6 Test  https://github.com/facebook/folly/issues/838: fs_util_test.Simple.UniquePath ..............................***Failed    0.12 sec
Note: Google Test filter = Simple.UniquePath
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Simple
[ RUN      ] Simple.UniquePath
```

After, works:
```
1920/1920 Test  https://github.com/facebook/folly/issues/813: parallel_test.ParallelTest.PSum ......................................................................   Passed   66.92 sec

100% tests passed, 0 tests failed out of 1919

Total Test time (real) =  67.02 sec

The following tests did not run:
        1348 - atomic_unordered_map_test.AtomicUnorderedInsertMap.MegaMap (Disabled)
```

Reviewed By: ndmitchell

Differential Revision: D59751594

Pulled By: ahornby

fbshipit-source-id: 6822abeb3ab73abd4643c2c680855f8f7ba61dbb