cut unused Singleton dep on RWSpinLock
Summary:
This dep prevents builds under some versions of MSVC and Clang in MSVC compatibility mode from using `Singleton`.

```
In file included from folly/Singleton.h:138:
folly\synchronization\RWSpinLock.h(581,19): error: anonymous structs are a GNU extension [-Werror,-Wgnu-anonymous-struct]
    __extension__ struct {
                  ^
```

Additionally, this mutex type uses the non-portable `__sync_...` family of functions which are GCC extensions also implemented by Clang, but which are not standard C++ and presumably not implemented by MSVC.

Reviewed By: Orvid

Differential Revision: D41295404

fbshipit-source-id: 7468a98c4810919fc5abf9eb15fe66fff36d9a0a