fix heap-vector value_compare under gcc
Summary:
Fixes the following error under some versions of gcc:
```
In file included from folly/container/test/heap_vector_types_test.cpp:26:
folly/container/heap_vector_types.h: In instantiation of ‘folly::type_t<bool, decltype (Compare::operator()(folly::detail::heap_vector_detail::value_compare_map::operator()::a.first ...))> folly::detail::heap_vector_detail::value_compare_map<Compare>::operator()(const value_type& ...) const [with value_type = {std::pair<int, int>, std::pair<int, int>}; Compare = std::less<int>; folly::type_t<bool, decltype (Compare::operator()(folly::detail::heap_vector_detail::value_compare_map::operator()::a.first ...))> = <type error>]’:
folly/container/test/heap_vector_types_test.cpp:54:5:   required from ‘void {anonymous}::check_invariant(Container&) [with Container = folly::heap_vector_map<int, int>]’
folly/container/test/heap_vector_types_test.cpp:326:24:   required from here
folly/container/heap_vector_types.h:651:44: error: cannot call member function ‘constexpr bool std::less<_Tp>::operator()(const _Tp&, const _Tp&) const [with _Tp = int]’ without object
       noexcept(noexcept(Compare::operator()(a.first...)))
                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```

In the code change, only the change to the `noexcept` bit is necessary for the fix, but the corresponding change to the return type is for consistency. For simplicity, we also presume that the parameter call-operator returns something sufficiently `bool`-like.

Reviewed By: Orvid

Differential Revision: D40960885

fbshipit-source-id: bf10164dd63ea8d3e7ccae18ea3f3991b37adc09