fix windows folly build (#2319)
Summary:
fix windows folly build
 * fmt requires unicode, add /utf-8 msvc flag
 * Settings.cpp build failed on SingletonRelaxedCounter, which needed Base::LocalLifetime as MSVC was ignoring the using typename and failing to build
 * MSVC can't handle the parameter to RegexMatchCache::is_span_compatible,  extract out the check that needs E to into the
std::enable_if_t
 * Disable tests that don't compile for windows for now. I see yfeldblum is working on fixing these in T205181491

Pull Request resolved: https://github.com/facebook/folly/pull/2319

Test Plan:
local build with: `python ./build/fbcode_builder/getdeps.py build --src-dir=. folly`

before, [broken](https://github.com/facebook/folly/actions/runs/11402111839/job/31726415001#step:42:629)
```
Z:\installed\fmt--08ZeFppBnK_Qz90kx-Yjd0crzRfSn6gIcQEVrX89l4\include\fmt\base.h(458): error C2338: Unicode support requires compiling with /utf-8
[2/842] Building CXX object CMakeFiles\folly_base.dir\folly\Conv.cpp.obj
```

then...
```
C:\Users\alex\local\folly\folly/container/RegexMatchCache.h(434): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'folly::detail::fallback_span::span<const size_t,18446744073709551615>'
C:\Users\alex\local\folly\folly/container/RegexMatchCache.h(434): note: No constructor could take the source type, or constructor overload resolution was ambiguous
ninja: build stopped: subcommand failed.
Command '['Y:\\build\\folly\\succeed.bat', '&&', 'Y:\\installed\\cmake-_qm1f2PWnzobdL5bp69h3vWFzt0Lbzikp_cDemrJG0U\\bin\\cmake.exe', '--build', 'Y:\\build\\folly', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed`
```

And finally, working.

**internal windows CI**

Before, [build broken](https://www.internalfb.com/sandcastle/workflow/4503599644332087)

After, now it builds green:
```
$ ./opensource/fbcode_builder/getdeps.py sandcastle folly --os-type windows
Mon 21 Oct 00:31:37 PDT 2024
[1/3] Getting the commit data from hg...
[2/3] Bundling and reading phabricator diffs...
[3/3] Starting Sandcastle jobs...
success the following Sandcastle job(s) were started:
```
https://www.internalfb.com/intern/sandcastle/job/18014400016957352/ - oss-folly-windows-getdeps for e822ec118bd9

Reviewed By: dtolnay

Differential Revision: D64604194

Pulled By: ahornby

fbshipit-source-id: ba6851110d007d736e39afc846d87bfc83b9f3f7