Cut unused sender_requires_from
Summary:
[Folly] Cut unused `sender_requires_from`.

Addresses shadowing violation under gcc5.

```
folly/experimental/pushmi/o/extension_operators.h: In lambda function:
folly/experimental/pushmi/o/extension_operators.h:236:381: error: declaration of 'auto:4 id' shadows a parameter [-Werror=shadow-local]
folly/experimental/pushmi/o/extension_operators.h:236:227: note: shadowed declaration is here```

Reviewed By: kirkshoop

Differential Revision: D13648907

fbshipit-source-id: 369bf3d0edce1065a5fe1dc2b1c20c7cdb25a0b4